name: trigger jenkins build
on: [push]
jobs:
  build-prod:
    name: Build-prod
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: trigger jenkins build
        uses: appleboy/jenkins-action@master
        with:
          url: ${{secrets.JENKINS_URL}}
          user: ${{secrets.JENKINS_USER}}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: '${{secrets.PROJECT_KEY}}_main'

  build-develop:
    name: Build-develop
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    steps:
      - name: trigger jenkins build
        uses: appleboy/jenkins-action@master
        with:
          url: ${{secrets.JENKINS_URL}}
          user: ${{secrets.JENKINS_USER}}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: '${{secrets.PROJECT_KEY}}_develop'

  build-qa:
    name: Build-qa
    runs-on: ubuntu-latest
    if: github.ref_name == 'qa'
    steps:
      - name: trigger jenkins build
        uses: appleboy/jenkins-action@master
        with:
          url: ${{secrets.JENKINS_URL}}
          user: ${{secrets.JENKINS_USER}}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: '${{secrets.PROJECT_KEY}}_qa'

  build-uat:
    name: Build-uat
    runs-on: ubuntu-latest
    if: github.ref_name == 'uat'
    steps:
      - name: trigger jenkins build
        uses: appleboy/jenkins-action@master
        with:
          url: ${{secrets.JENKINS_URL}}
          user: ${{secrets.JENKINS_USER}}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: '${{secrets.PROJECT_KEY}}_uat'
