name: trigger jenkins build
on: [push]
jobs:
  build-prod:
    name: Build-prod
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: trigger jenkins build
        uses: appleboy/jenkins-action@master
        with:
          url: 'https://cicd.champsoft.com/pipeline'
          user: 'tharukag'
          token: ${{ secrets.JENKINS_TOKEN }}
          job: 'Github_Pipeline_main'

  build-prod:
    name: Build-develop
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    steps:
      - name: trigger jenkins build
        uses: appleboy/jenkins-action@master
        with:
          url: 'https://cicd.champsoft.com/pipeline'
          user: 'tharukag'
          token: ${{ secrets.JENKINS_TOKEN }}
          job: 'Github_Pipeline_develop'
